# Generated by Django 6.0.7 on 2026-08-03 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
