# Generated by Django 6.0.7 on 2026-09-09 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.order'),
            preserve_default=False,
        ),
    ]
