# Generated by Django 6.0.7 on 2026-09-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email_address', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('physical_address', models.TextField(blank=True, default='', null=True)),
                ('address_type', models.TextField(blank=True, default='', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=9, null=True)),
                ('delivery_radius', models.FloatField(default=0.0, help_text='In KM')),
                ('footer_description', models.TextField(blank=True, default='', null=True)),
                ('working_hours_mon_sat', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('working_hours_sunday', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('opening_time', models.TimeField(blank=True, help_text='Format: HH:MM:SS', null=True)),
                ('closing_time', models.TimeField(blank=True, help_text='Format: HH:MM:SS', null=True)),
                ('is_manually_open', models.BooleanField(default=True, help_text='Turn OFF to manually close the restaurant immediately.')),
                ('instagram_url', models.URLField(blank=True, default='', max_length=500, null=True)),
                ('facebook_url', models.URLField(blank=True, default='', max_length=500, null=True)),
                ('twitter_url', models.URLField(blank=True, default='', max_length=500, null=True)),
                ('whatsapp_url', models.URLField(blank=True, default='', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
