# Generated by Django 6.0.7 on 2026-08-03 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('orders', '0002_remove_orderitem_order_remove_orderitem_food_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('ALL', 'All'), ('BANNER', 'Banner'), ('COMBO MENU', 'Combo Menu'), ('BEST SELLER', 'Best Seller'), ("TODAY'S SPECIAL", "Today's Special"), ('OTHERS', 'Others')], default='ALL', max_length=50)),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/', verbose_name='Product Image')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banner_images/', verbose_name='Banner Image')),
                ('dietary_preference', models.CharField(choices=[('VEG', 'Veg'), ('NON-VEG', 'Non-Veg')], default='VEG', max_length=10)),
                ('has_variants', models.BooleanField(default=False, verbose_name='Has Sizes/Variants?')),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Actual ₹')),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Offer ₹')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Qty')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.category')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=50)),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Actual ₹')),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Offer ₹')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Qty / Stock')),
                ('is_available', models.BooleanField(default=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='menu.menuitem')),
            ],
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
