# Generated by Django 6.0.7 on 2026-09-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_image_alter_category_name_menuitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='banner_image',
        ),
    ]
