# Generated by Django 6.0.7 on 2026-08-03 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delete_delivery'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='food_item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
